services:
  frontend:
    build:
      context: ./Frontend # Path to the directory containing the frontend Dockerfile
    ports: 
      - "80:80"
    networks:
      - todonetwork

  backend:
    build:
      context: ./Backend # Path to the directory containing the frontend Dockerfile
    ports: 
      - "9000:8080"
    networks:
      - todonetwork

  # Database Service
  db:
    build:
      context: ./DatabasePostgres  # Path to the directory containing the database Dockerfile
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=gammelfleisch1
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"  # Expose database port for external access if needed
    networks:
      - todonetwork
networks:
  todonetwork:
    driver: bridge